# Generated by Django 4.1.5 on 2023-01-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessrook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgames',
            old_name='player_name',
            new_name='player',
        ),
    ]
