# Generated by Django 4.1.5 on 2023-01-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessrook', '0002_rename_player_name_chessgames_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgames',
            name='game_notes',
            field=models.CharField(default='none_notes', max_length=5000),
        ),
    ]
