# Generated by Django 4.1.5 on 2023-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessrook', '0003_chessgames_game_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgames',
            name='game_name',
            field=models.CharField(max_length=50),
        ),
    ]
